all:
	g++ -Wall -Werror -std=c++11 src/Recognized_Token_Object.cpp src/Microphone_Object.cpp src/Table_Object.cpp src/Table_Visualizer.cpp src/main.cpp  -o bin/table_visualizer_app -lfftw3_threads -lfftw3 -lm -lsfml-graphics -lsfml-window -lsfml-system -lsndfile
	#src/Table_Object.cpp src/Table_Visualizer.cpp
