all:
	#g++ -Wall -Werror -std=c++11 src/visualizer_main.cpp -o bin/SignalTransform -lfftw3 -lm -lsfml-graphics -lsfml-window -lsfml-system
	#g++ -c -Wall -Werror -std=c++11  
	g++ -Wall -Werror -std=c++11  src/FFT_Transformer.cpp src/ring_buffer.cpp src/main.cpp  -o bin/buffer_transform_test -lfftw3_threads -lfftw3 -lm -lsfml-graphics -lsfml-window -lsfml-system -lsndfile

